### ISSUE TITLE
question: multiple exit classes?

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [Marc-Bernard-Tools/ABAP-Lint-Ext-for-abapGit#2]
I'm already using [Sandra's rfc logon exit](https://github.com/sandraros/abapGit-user-exit-logon-by-rfc).
abapGit's ZCL_ABAPGIT_EXIT is not set up to handle multiple implementation classes.

The way I understand it, I have to modify that class, correct?

**Comment by mbtools** [comment]
yes, you have to combine the methods into `zcl_abapgit_user_exit`. from there you could of course call other classes.

putting `zcl_abapgit_user_exit` into a repo with some exit coding isn't the best idea since pulling would overwrite whatever other exit methods you already use. 

maybe one day we enhance `zcl_abapgit_exit` to call all implementations of the `zif_abapgit_exit` interface and not just `zcl_abapgit_user_exit`

**Comment by AndreaBorgia-Abo** [comment]
Ok, thanks.
